package exception;

public class TestException2 {
public static void main(String[] args) {
int num1 = 20;
int num2 = 0;

int x = num1 / num2;
System.out.println(x);
System.out.println("Program ends");
}
}

//java created obj for ArithmeticException